### ISSUE TITLE
Remove require package.json

### ISSUE THREAD

**Issue by cardinaltm** [rpallas/impala-js#12]
Hello,
Please remove this code from this file, some projects are in production, need compilation, and because it requires package.json, the project does not compile to executable bin file, have to manually delete this code each time.

/src/api.js
```
const { name, version } = require(Path.join(process.cwd(), 'package.json'))
const userAgent = `${name}/${version}`

'User-Agent': userAgent,
```

**Comment by rpallas** [comment]
Hi @cardinaltm,

Apologies for the long wait.

I've added an option to disable the user-agent header. I hope this fixes your issue.

You can use it like this:

```
const impala = ImpalaSDK.create('api-key', { useragent: false });
```
